### ISSUE TITLE
from config import Setting

### ISSUE THREAD

**Issue by bsailer2510** [innoveit/python-dhl-api#3]
Good Morning! Looks like that the required [config](https://docs.red-dove.com/cfg/python.html) Package does not contain a Class "Setting" (anymore).
With that the script fails allready at the Import.

`ImportError: cannot import name 'Setting' from 'config' (C:\Users\bernh\anaconda3\lib\site-packages\config\__init__.py)`

**Comment by matteomunaretto** [comment]
Hi, you can directly put your DHL keys for using the service like:
`service = DHLService(api_key="your DHL_API_KEY", api_secret="your DHL_API_SECRET", ...`

Or rename the __config_template.py_ to _config.py_ and add your DHL keys.
